version: 2.1
orbs:
  node: circleci/node@1.1.6
  coverage-reporter: codacy/coverage-reporter@10.0.3
jobs:
  checkout:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
  test:
    executor:
      name: node/default
    steps:
      - run: npm test
      - coverage-reporter/send_report:
          coverage-reports: "coverage/lcov.info"
          project-token: ${CODACY_PROJECT_TOKEN}
  package:
    executor:
      name: node/default
    steps:
      - run: npm run compile
  pre-deploy:
    executor:
      name: node/default
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  deploy:
    executor:
      name: node/default
    steps:
      - run: npm publish
  deploy-rc:
    executor:
      name: node/default
    steps:
      - run: npm publish --tag rc
workflows:
  build-test-package-deploy:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - package:
          requires:
            - test
      - pre-deploy:
          requires:
            - package
      - deploy:
          requires:
            - pre-deploy
          filters:
            tags:
              only: /\d+\.{1}\d+.{1}\d+/
            branches:
              ignore: /.*/
      - deploy-rc:
          requires:
            - pre-deploy
          filters:
            tags:
              only: /\d+\.{1}\d+.{1}\d+-{1}.*/
            branches:
              ignore: /.*/
